#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);

my $CGI = exists $ENV{'GATEWAY_INTERFACE'} ? 1 : 0;
my $postdata = undef;

if ($CGI) {
    $postdata = &get_cgi_query();
} else {
    $postdata = "ran from command line";
}

print "Content-type: application/xml\n\n";
print "<headers>\n";

foreach my $key (sort keys %ENV) {
    next if $key !~ /^HTTP_(.*)/;
    print "  <header name='$1' value='", $ENV{$key}, "'/>\n";
}

print "</headers>\n";

exit(0);

# ----------------------------------------------------------------------

sub get_cgi_query {
    local $_;

    if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	read(STDIN, $_, $ENV{'CONTENT_LENGTH'});
    } else {
	$_ = $ENV{'QUERY_STRING'};
    }

    return $_;
}


