#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);

# To satisfy Apache, always read the input
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
    read(STDIN, $_, $ENV{'CONTENT_LENGTH'});
}

print "Content-type: image/png\n\n";

open (F, "/usr/local/apache2/htdocs/docs/helloworld.png");
binmode F;
while (read(F, $_, 4096)) {
    print $_;
}
close (F);

exit(0);
