#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);

# To satisfy Apache, always read the input
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
    read(STDIN, $_, $ENV{'CONTENT_LENGTH'});
}

print "Content-type: application/rdf+xml\n\n";
print "<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'\n";
print "         xmlns:dc='http://purl.org/dc/elements/1.1/'>\n";
print "  <rdf:Description rdf:about=''>\n";
print "    <dc:title>Hello world!</dc:title>\n";
print "  </rdf:Description>\n";
print "</rdf:RDF>\n";

exit(0);
