#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);

# To satisfy Apache, always read the input
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
    read(STDIN, $_, $ENV{'CONTENT_LENGTH'});
}

print "Content-type: text/plain\n\n";
print "Hello world!\n";

exit(0);
