#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);
use CGI::Cookie;

my $CGI = exists $ENV{'GATEWAY_INTERFACE'} ? 1 : 0;

my $cookie1 = new CGI::Cookie(-name => "One", -value => "1");
my $cookie2 = new CGI::Cookie(-name => "Two",
                              -path => "/service",
                              -value => "2");
my $cookie3 = new CGI::Cookie(-name => "Three",
                              -expires => "+3M",
                              -value => "1");

print "Set-Cookie: $cookie1\n";
#print "Set-Cookie: $cookie2\n";
#print "Set-Cookie: $cookie3\n";
print "Content-type: text/plain\n\n";
print "I gave you some cookies.\n";

exit(0);
