#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);

my $CGI = exists $ENV{'GATEWAY_INTERFACE'} ? 1 : 0;
my $postdata = undef;

if ($CGI) {
    $postdata = &get_cgi_query();
} else {
    $postdata = "ran from command line";
}

print "Content-type: ", $ENV{'CONTENT_TYPE'} || "text/plain", "\n\n";
print $postdata;

exit(0);

# ----------------------------------------------------------------------

sub get_cgi_query {
    local $_;

    if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	read(STDIN, $_, $ENV{'CONTENT_LENGTH'});
    } else {
	$_ = $ENV{'QUERY_STRING'};
    }

    return $_;
}


