#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);

# To satisfy Apache, always read the input
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
    read(STDIN, $_, $ENV{'CONTENT_LENGTH'});
}

print "Content-type: text/html\n\n";
print "<!DOCTYPE html>\n";
print "<html xmlns='http://www.w3.org/1999/xhtml'>\n";
print "<head>\n";
print "<title>Example document</title>\n";
print "</head>\n";
print "<body>\n";
print "<h1>Example document</h1>\n";
print "<p>This is an <a href='https://en.wikipedia.org/wiki/HTML5'>HTML</a> document.\n";
print "</p>\n";
print "</body>\n";
print "</html>\n";

exit(0);
