#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);

# To satisfy Apache, always read the input
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
    read(STDIN, $_, $ENV{'CONTENT_LENGTH'});
}

sleep(10);

print "Content-type: application/xml\n\n";
print "<doc><title>Sample document</title>\n";
print "<p>“Hello, world,” he said, slowly.</p>\n";
print "</doc>\n";

exit(0);
