#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;
use CGI::Carp qw(fatalsToBrowser);
use CGI::Cookie;

my $CGI = exists $ENV{'GATEWAY_INTERFACE'} ? 1 : 0;

my $cookie = new CGI::Cookie(-name => "a-goes-to", -value => "b");

my $redirect = "http://" . $ENV{'HTTP_HOST'} . "/service/this-is-b";

print "Set-Cookie: $cookie\n";
print "Status: 302 Moved\n";
print "Location: $redirect\n\n";

exit(0);
